Add missing docs BuildRequires
    Exception in .../docs/source/sphinxext.rst at block ending on line 162
    Specify :okexcept: as an option in the ipython:: block to suppress this message
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    ...
    ----> 1 import numpy.random
    ModuleNotFoundError: No module named 'numpy'

    Exception in .../docs/source/sphinxext.rst at block ending on line None
    Specify :okexcept: as an option in the ipython:: block to suppress this message
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    ...
    ----> 1 from matplotlib.pylab import *
    ModuleNotFoundError: No module named 'matplotlib'